- name: copying the mongo repo 
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo # /etc/yum.repos.d/mongo.repo

    
- name: install mongodb server
  ansible.builtin.dnf:
    name: mongodb-org #mongodb-org-6.0
    state: present

# - name : starting  the mongodb server
#   ansible.builtin.service:
#     name : mongodb 
#     state: present
#     started: yes

- name: allow remote connection
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

# - name : restarting  the mongodb
#   ansible.builtin.service:
#     name : mongodb
#     enabled : yes 
#     state: started

- name : enable the mongodb
  ansible.builtin.service:
    name : mongod
    enabled : yes 
    state: started